/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateMilestoneArgs } from "./CreateMilestoneArgs";
import { UpdateMilestoneArgs } from "./UpdateMilestoneArgs";
import { DeleteMilestoneArgs } from "./DeleteMilestoneArgs";
import { MilestoneFindManyArgs } from "./MilestoneFindManyArgs";
import { MilestoneFindUniqueArgs } from "./MilestoneFindUniqueArgs";
import { Milestone } from "./Milestone";
import { TaskFindManyArgs } from "../../task/base/TaskFindManyArgs";
import { Task } from "../../task/base/Task";
import { Project } from "../../project/base/Project";
import { MilestoneService } from "../milestone.service";

@graphql.Resolver(() => Milestone)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class MilestoneResolverBase {
  constructor(
    protected readonly service: MilestoneService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Milestone",
    action: "read",
    possession: "any",
  })
  async _milestonesMeta(
    @graphql.Args() args: MilestoneFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Milestone])
  @nestAccessControl.UseRoles({
    resource: "Milestone",
    action: "read",
    possession: "any",
  })
  async milestones(
    @graphql.Args() args: MilestoneFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Milestone[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Milestone",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Milestone, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Milestone",
    action: "read",
    possession: "own",
  })
  async milestone(
    @graphql.Args() args: MilestoneFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Milestone | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Milestone",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Milestone)
  @nestAccessControl.UseRoles({
    resource: "Milestone",
    action: "create",
    possession: "any",
  })
  async createMilestone(
    @graphql.Args() args: CreateMilestoneArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Milestone> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Milestone",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Milestone"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        project: args.data.project
          ? {
              connect: args.data.project,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Milestone)
  @nestAccessControl.UseRoles({
    resource: "Milestone",
    action: "update",
    possession: "any",
  })
  async updateMilestone(
    @graphql.Args() args: UpdateMilestoneArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Milestone | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Milestone",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Milestone"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          project: args.data.project
            ? {
                connect: args.data.project,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Milestone)
  @nestAccessControl.UseRoles({
    resource: "Milestone",
    action: "delete",
    possession: "any",
  })
  async deleteMilestone(
    @graphql.Args() args: DeleteMilestoneArgs
  ): Promise<Milestone | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Task])
  @nestAccessControl.UseRoles({
    resource: "Milestone",
    action: "read",
    possession: "any",
  })
  async tasks(
    @graphql.Parent() parent: Milestone,
    @graphql.Args() args: TaskFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Task[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Task",
    });
    const results = await this.service.findTasks(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => Project, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Milestone",
    action: "read",
    possession: "any",
  })
  async project(
    @graphql.Parent() parent: Milestone,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Project | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Project",
    });
    const result = await this.service.getProject(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
